### PR TITLE
Prepare for release 0.3.0

### PR DESCRIPTION
**Pull request by vic**
[Release](https://github.com/asdf-community/asdf-direnv/releases/tag/untagged-abc814be7144778e9e3e) once these get merged:

- [x] #130

### CODE REVIEW

**Comment by vic** [comment]
Please add any other relevant PR that might enter the release. We've been doing a lot of improvements to the setup so if anyone still finds we can improve documentation, some code we can wait a bit for release.

**Review by jfly — APPROVED** [review]
LGTM, pending the merge of #130

I don't know of any documentation changes.

I have a couple of coworkers who use `asdf-direnv` at work (I'm slowly trying to get the whole team to switch from vanilla `asdf`). I can ask them to try upgrading before or right after release, depending on how careful you want to be with this change.

I'm actually a little unclear on what exactly the impact of tagging releases is on our users. Does `asdf plugin update` pay any attention to release tags? I was under the impression that it just pulls that latest code of each plugin...

**Comment by vic** [comment]
> I'm actually a little unclear on what exactly the impact of tagging releases is on our users. Does `asdf plugin update` pay any attention to release tags? I was under the impression that it just pulls that latest code of each plugin...

Yep, AFAIK `asdf plugin-add` does not support you to specify a git-ref and it will just clones the default branch. Perhaps that could be a good thing to contribute to asdf-vm.

However I still see value in having releases from time to time. At least as a way to communicate we have reached a milestone, or completed a set of changes that significantly improve user-experience.

Currently we've been working on PRs and merging (and sometimes hot-fixing) on master directly. For bug fixes that is a good thing since people will just pull and get the fixes, however if we introduce breaking behaviour -like we did on changing our setup in #130 and other previous PRs- people not-in-the-loop of what's happening on this repo might get unexpected surprises. Even more if we rapidly iterate and one day we have interactive setup and the other we don't - it's a good thing that we can change our minds and improve rapidly - I'm a bit more worried about user's experience here and the stability (from a ux side of view) of master branch.

Perhaps we could keep master for releases and hot-fixes only. And have a `develop` branch were committers can work and merge new/breaking features. Previously we had [features](https://github.com/asdf-community/asdf-direnv/releases/tag/0.1.0) were I asked people to help using the new features before merging into master (unfortunately I had no chance to merge until like ~7months later).

Next release we'll probably remove support for installing direnv versions and perhaps having PRs merged on master immediately would not be a good idea. Dunno, I'm open to suggestions on all of this.
 
So that's mainly my motivation for having releases and also a Changelog.

**Comment by vic** [comment]
> I have a couple of coworkers who use `asdf-direnv` at work (I'm slowly trying to get the whole team to switch from vanilla `asdf`). I can ask them to try upgrading before or right after release, depending on how careful you want to be with this change.

That would be great! The more people that can test new features the better. :)

**Pull request merged**
