### PR TITLE
WIP: Recursive sourcing of .tool-versions and small things

### PR DESCRIPTION
**Pull request by michi-zuri**
This plugin currently ignores global asdf tools when a local environment is loaded. Without this plugin, all versions are stacked, this pull request implements recursive sourcing of all .tool-versions and adds an option to disable this for specific environments.

### CODE REVIEW

**Comment by imbsky** [comment]
Rebased.

**Comment by vic** [comment]
Hey @michi-zuri, your proposal makes a lot of sense since when you execute a normal asdf-shim, asdf will traverse directories up looking for the tool version. If I recall correctly, it traverses up to / and then fallbacks to $HOME/.tool-versions) could you test if this is still the case?


But I think we have some things to consider:

Suppose you have 

```
/home/user
   .tool-versions  { pluginA=1.0, pluginB=1.0 }

   hobby-project/
       .tool-versions { pluginD=1.0 }
       .envrc { use asdf exclusive }

/work/some/project
     .tool-versions { pluginA=2.0, pluginC=1.0 }
     .envrc { use asdf }
```

We have to make sure that the activated environment when entering `some/project` will be
pluginA=2.0, pluginC=1.0, pluginB=1.0  in that order.

Probably it's now the time to finally add some `bats` test with some dummy plugins to make sure we have tests for this behaviour. The idea is that with this direnv plugin users should have the exact same environment than using bare asdf shims.

**Comment by michi-zuri** [comment]
I didn't realize that the global file was sourced even outside the home directory, will test for that! I have no idea what bats tests are though. 

What I found interesting is that the version itself is decided upon by `asdf which` and in the example someproject above we are actually putting version 2.0 in PATH twice.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vic** [comment]
@michi-zuri I've been working on a new branch #14, definitely based on your approach, but instead of trying to resolve versions and lookup for files myself, I'm using asdf core functions to resolve versions.

I'll close this branch and continue work in #14.

**Comment by imbsky** [comment]
@all-contributors please add @michi-zuri for ideas

**Pull request closed without merging**
