### PR TITLE
Fix 'direnv: command not found'

### LINKED ISSUE #32: direnv_use_asdf: line 92: direnv: command not found`
Hey,

I have a `.envrc` inside my home directory, as I want the globally installed plugins to be loaded by default.

When executing `which node` i get the error `/Users/omares/.asdf/plugins/direnv/bin/direnv_use_asdf: line 92: direnv: command not found`. The full output can be seen below.

My system does not have `direnv` globally installed and it seems this plugin only provides direnv via the `asdf exec direnv...` call. [Shouldn't the affected code line reflect this](https://github.com/asdf-community/asdf-direnv/blob/master/bin/direnv_use_asdf#L92)? Or did is miss something when installing the direnv plugin?

```
asdf current
direnv         2.20.0   (set by /Users/omares/.tool-versions)
java           adopt-openjdk-11.0.5+10 (set by /Users/omares/.tool-versions)
maven          3.6.3    (set by /Users/omares/.tool-versions)
nodejs         10.17.0  (set by /Users/omares/.tool-versions)
python         3.8.0    (set by /Users/omares/.tool-versions)
ruby           2.6.5    (set by /Users/omares/.tool-versions)
```

```
which node
/usr/local/bin/node
direnv: loading .envrc
direnv: using asdf
/Users/omares/.asdf/plugins/direnv/bin/direnv_use_asdf: line 92: direnv: command not found
direnv: loading ~/.asdf/installs/direnv/2.20.0/env/1337337645-3443856708-4294967295-1908856927
direnv: using asdf direnv 2.20.0
```

### PR DESCRIPTION
**Pull request by omares**
Fixes #32

### CODE REVIEW

**Comment by vic** [comment]
Actually, since the direnv stdlib is loaded at the start of the file, we could also use `$direnv` and that would point to the already resolved executable. Could you test replacing `asdf exec direnv` with just expanding `$direnv` ?

**Comment by omares** [comment]
Done :) tested locally and it seems to work so far.

**Comment by vic** [comment]
Nice, thank you!, just fix the `lint` check and we are good to merge :)

**Comment by imbsky** [comment]
@vic @omares Fixed.

**Comment by omares** [comment]
thank you @imbsky

**Comment by vic** [comment]
@all-contributors please add @omares  for code

**Pull request merged**
