### PR TITLE
Make `asdf direnv setup` more robust

### PR DESCRIPTION
**Pull request by jfly**
`grep_or_add` just isn't the most robust thing: when dealing with
multiple lines, it only cares about being able to find *one* of the
lines, rather than all of the lines. That could cause issues if we ever
change what our setup script does, or if someone runs our setup script
twice with slightly different arguments (such as when first installing
asdf-direnv, and then later wanting to upgrade to the latest version of
direnv).

With this new approach, we take 100% control over various asdf-direnv
specific files, and only use `grep_or_add` to get bash and zsh to load
`~/.config/asdf-direnv/{bashrc,zshrc}`.

### CODE REVIEW

**Comment by vic** [comment]
Let's wait for all comments on #129 to be fixed and merged before reviewing this. (Or change the merge target not to be master but the branch from #129)

**Comment by jfly** [comment]
> change the merge target not to be master but the branch from

Yeah, I would do that, but I'm doing my work in a fork, and I don't think it's possible to do that =(

I'm in no rush here, I think it's ok for this to wait until #129 is merged up. (I just wanted you to know that I was working on this!)

**Comment by vic** [comment]
Please rebase on master.

**Comment by jfly** [comment]
Rebased!

**Comment by vic** [comment]
thanks!

**Pull request merged**
