### PR TITLE
Save the fish config to `$__fish_user_data_dir`

### PR DESCRIPTION
**Pull request by kabouzeid**
This path makes more sense and doesn't clutter the user's dotfiles.

See also: https://fishshell.com/docs/current/language.html#configuration-files

### CODE REVIEW

**Review by jfly — COMMENTED** [review]
Interesting that fish considers this "data" rather than config. But reading the docs you linked to, this seems like a reasonable interpretation.

What will this do to people who had previously run an older version of the setup script? Will they end up with 2 files that get sourced by fish on startup? That doesn't feel good to me. I think we should clean up the old file or give a warning/error if it exists.

**Comment by kabouzeid** [comment]
I'd consider it `data` because it is autogenerated and not meant to be edited by the user. Clean up is not strictly necessary because the new location will be sourced after the old location. But I agree, it'd be best to remove the old file.

**Comment by kabouzeid** [comment]
I've added clean-up code + a small sanity as to not accidentaly delete a user created file.

**Comment by jfly** [comment]
Thanks!

**Pull request merged**
